# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-09 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterModelTable(
            name='question',
            table='blogposts',
        ),
    ]
